# rename this file as ~/.config/vocabnb/config.toml to take effect
total_sample = 50
min_sample = 10
do_pronounce = false
dbfile = "~/Documents/words.db"
cachedir = "~/.cache/vocabnb"
mwapi = "**************"
